// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8OS6BQ1oj5JJYrYxDmUHDNakf1zP0HM',
    appId: '1:978047623886:web:e6c73d83c47695c104269f',
    messagingSenderId: '978047623886',
    projectId: 'mucha-flutter',
    authDomain: 'mucha-flutter.firebaseapp.com',
    storageBucket: 'mucha-flutter.appspot.com',
    measurementId: 'G-9FXYLKYX90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFDvrQS0eFIotr4NNgVwo9eSqupW2gxYQ',
    appId: '1:978047623886:android:3e85b130df04d79d04269f',
    messagingSenderId: '978047623886',
    projectId: 'mucha-flutter',
    storageBucket: 'mucha-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFTTDi-OigbDWJT7mfEnQB3kGEHC620QY',
    appId: '1:978047623886:ios:9d6f565755af9ab804269f',
    messagingSenderId: '978047623886',
    projectId: 'mucha-flutter',
    storageBucket: 'mucha-flutter.appspot.com',
    iosBundleId: 'com.muchanaibei.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFTTDi-OigbDWJT7mfEnQB3kGEHC620QY',
    appId: '1:978047623886:ios:b8d0fdaa9046ee2e04269f',
    messagingSenderId: '978047623886',
    projectId: 'mucha-flutter',
    storageBucket: 'mucha-flutter.appspot.com',
    iosBundleId: 'com.muchanaibei.flutterLearning.RunnerTests',
  );
}
